version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sqlalchemy
    versions:
    - 1.4.0
    - 1.4.1
    - 1.4.2
    - 1.4.3
    - 1.4.4
    - 1.4.5
    - 1.4.6
    - 1.4.7
    - 1.4.8
    - 1.4.9
  - dependency-name: twilio
    versions:
    - 6.53.0
    - 6.54.0
    - 6.55.0
    - 6.56.0
  - dependency-name: regex
    versions:
    - 2021.3.17
  - dependency-name: flake8
    versions:
    - 3.9.0
  - dependency-name: pyflakes
    versions:
    - 2.3.0
  - dependency-name: alembic
    versions:
    - 1.5.6
    - 1.5.7
  - dependency-name: pyjwt
    versions:
    - 2.0.1
  - dependency-name: flask-migrate
    versions:
    - 2.6.0
    - 2.7.0
  - dependency-name: httplib2
    versions:
    - 0.18.0
    - 0.19.0
  - dependency-name: six
    versions:
    - 1.15.0
  - dependency-name: flask
    versions:
    - "1.0"
  - dependency-name: flask-wtf
    versions:
    - 0.14.3
  - dependency-name: werkzeug
    versions:
    - 0.15.3
  - dependency-name: flask-script
    versions:
    - 2.0.6
  - dependency-name: jinja2
    versions:
    - 2.10.1
  - dependency-name: python-editor
    versions:
    - 1.0.4
  - dependency-name: itsdangerous
    versions:
    - 1.1.0
  - dependency-name: funcsigs
    versions:
    - 1.0.2
